"""initial schema

Revision ID: 20bd574fd49e
Revises:
Create Date: 2026-09-30 12:10:02.521735
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20bd574fd49e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch",
        sa.Column("batch_key", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("business_type", sa.String(length=128), nullable=True),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=True),
        sa.Column("source_licence", sa.String(length=128), nullable=True),
        sa.Column("sampling_method", sa.Text(), nullable=True),
        sa.Column("sampling_seed", sa.Integer(), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observation_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_key"),
    )
    op.create_table(
        "lead",
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("postcode", sa.String(length=16), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("website_source", sa.String(length=128), nullable=True),
        sa.Column(
            "screening_class",
            sa.Enum(
                "unchecked",
                "candidate",
                "unknown",
                "excluded_cafe",
                "excluded_chain",
                "excluded_canteen",
                "excluded_community",
                "excluded_institution",
                "excluded_pub",
                "excluded_closed",
                "excluded_other",
                name="screening_class",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("screening_reason", sa.Text(), nullable=True),
        sa.Column(
            "entity_status",
            sa.Enum("unknown", "company", "sole_trader", "other", name="entity_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("entity_evidence", sa.Text(), nullable=True),
        sa.Column("entity_reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_table(
        "operator",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_log",
        sa.Column("operator_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "batch_lead",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("sample_order", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["batch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "lead_id", name="uq_batch_lead"),
    )
    op.create_table(
        "channel_eligibility",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "whatsapp",
                "phone",
                "instagram",
                "contact_form",
                "post",
                name="channel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("contact_ref", sa.String(length=256), nullable=True),
        sa.Column("contact_source", sa.String(length=256), nullable=True),
        sa.Column("contact_collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "contact_usable",
            sa.Enum("unknown", "valid", "invalid", name="contact_usable", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column(
            "eligibility",
            sa.Enum("unknown", "allowed", "blocked", name="eligibility", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("rule_version", sa.String(length=64), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cost_entry",
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("setup", "processing", "outreach", name="cost_category", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column("basis", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "whatsapp",
                "phone",
                "instagram",
                "contact_form",
                "post",
                name="channel",
                native_enum=False,
                length=40,
            ),
            nullable=True,
        ),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "reply", "reject", "unsubscribe", "bounce", "note", name="event_kind", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.String(length=64), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_table(
        "import_run",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=256), nullable=True),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("linked_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("operator", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_asset",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("html", "pdf", "image", "unknown", name="asset_kind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("final_url", sa.String(length=1024), nullable=True),
        sa.Column("original_filename", sa.String(length=256), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.String(length=512), nullable=True),
        sa.Column(
            "fetch_status",
            sa.Enum("pending", "fetched", "failed", name="fetch_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("fetch_attempts", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("added_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_analysis",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "needs_review",
                "failed",
                name="analysis_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("engine", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("measurements", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("review_state", sa.String(length=32), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_sha256", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["menu_asset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "version", name="uq_analysis_version"),
    )
    op.create_table(
        "suppression",
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column(
            "scope", sa.Enum("lead", "contact", name="suppression_scope", native_enum=False, length=40), nullable=False
        ),
        sa.Column("contact_ref", sa.String(length=256), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis_correction",
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column("field_path", sa.String(length=256), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("corrected_by", sa.String(length=64), nullable=False),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["menu_analysis.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_piece",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("sample_partial", "message_short", name="content_kind", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template_name", sa.String(length=128), nullable=True),
        sa.Column("template_version", sa.String(length=64), nullable=True),
        sa.Column("engine", sa.String(length=64), nullable=True),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("storage_path_html", sa.String(length=512), nullable=True),
        sa.Column("storage_path_png", sa.String(length=512), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "approved", "rejected", name="content_status", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["menu_analysis.id"],
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lead_id", "kind", "version", name="uq_content_version"),
    )
    op.create_table(
        "approval",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("approved", "rejected", name="approval_decision", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("decided_by", sa.String(length=64), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_piece.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manual_task",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "whatsapp",
                "phone",
                "instagram",
                "contact_form",
                "post",
                name="channel",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("eligibility_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "opened",
                "sent_manual",
                "paused",
                "cancelled",
                name="task_status",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_by", sa.String(length=64), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_by", sa.String(length=64), nullable=True),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content_piece.id"],
        ),
        sa.ForeignKeyConstraint(
            ["eligibility_id"],
            ["channel_eligibility.id"],
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["lead.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manual_task")
    op.drop_table("approval")
    op.drop_table("content_piece")
    op.drop_table("analysis_correction")
    op.drop_table("suppression")
    op.drop_table("menu_analysis")
    op.drop_table("menu_asset")
    op.drop_table("import_run")
    op.drop_table("event")
    op.drop_table("cost_entry")
    op.drop_table("channel_eligibility")
    op.drop_table("batch_lead")
    op.drop_table("audit_log")
    op.drop_table("operator")
    op.drop_table("lead")
    op.drop_table("batch")
    # ### end Alembic commands ###
